name: push-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') || github.ref == 'refs/heads/ci'
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test ./...
